### ISSUE TITLE
Setup Project

### ISSUE THREAD

**Issue by LauraBeatris** [DenoBrazil/denobrazil.com#3]
# Description

Setup project with NextJS and TypeScript

# Tasks

- [x] Initialize project with ``npx create-next-app denobrazil`` and push the content to this remote repository.
- [x] Setup TypeScript 
- [x] Configure translations (Make sure to support English & Portuguese)
- [x] Remove all the unused content that come with the default template from ``create-next-app``
- [x] Setup vercel for automatic deploy along the PRs 

# Notes

- [How to setup a NextJS project with ``create-nextjs-app``](https://nextjs.org/learn/basics/create-nextjs-app/setup) 
- [How to setup ``TypeScript`` on a NextJS project](https://nextjs.org/learn/excel/typescript)
- [Helpful package to configure translations with ``i18n`` on a NextJS project](https://github.com/isaachinman/next-i18next)

# Clarifications
There's no need to configure tools such as ``eslint`` for now, it'll be implemented on another issue.
