### ISSUE TITLE
Setup base style guide

### ISSUE THREAD

**Issue by LauraBeatris** [DenoBrazil/denobrazil.com#4]
# Description

Setup base style guide and dependencies.

https://www.figma.com/file/XeLPQDZAXRbQQAS0NFUdbn/Deno?node-id=0%3A1

# Tasks

* [x] Setup [Chakra UI](https://chakra-ui.com/)

* [x] Define base theme file + provider ([docs](https://chakra-ui.com/theme))

* [x] Add logo assets

* [x] Add font assets

* [x] Define color palette

* [x] Define typography

* [x] Define standard margins / layout proportions
