### ISSUE TITLE
Setup code standarts and absolute imports

### ISSUE THREAD

**Issue by LauraBeatris** [DenoBrazil/denobrazil.com#5]
# Description 

Setup tools to maintain standards along the code base, related to code style and good practices. 

# Tasks 

- [x] Setup [@jungsoft/eslint-config](github.com/jungsoft/eslint-config) - Make sure to follow the installation instructions
- [ ] Setup [husky](https://github.com/typicode/husky), [lintstaged](https://github.com/okonet/lint-staged) and [commitlint](https://github.com/conventional-changelog/commitlint)
- [x] Setup absolute imports 

# Notes 

- [How to setup absolute imports on NextJS project that uses TS](https://nextjs.org/docs/advanced-features/module-path-aliases)
